# Generated by Django 2.2.7 on 2019-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavirtual', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagentest',
            field=models.ImageField(blank=True, null=True, upload_to='img_prod/'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='estadopago',
            field=models.CharField(choices=[('a', 'Aprovado'), ('p', 'Pendiente'), ('r', 'Rechazado')], db_column='EstadoPago', max_length=1),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='formapago',
            field=models.CharField(choices=[('e', 'Efectivo'), ('d', 'Depósito')], db_column='FormaPago', max_length=1),
        ),
        migrations.AlterField(
            model_name='productos',
            name='demanda',
            field=models.CharField(choices=[('b', 'Bajo'), ('m', 'Medio'), ('a', 'Alto')], db_column='Demanda', max_length=1),
        ),
        migrations.AlterField(
            model_name='productos',
            name='suspendido',
            field=models.CharField(choices=[('s', 'Sí'), ('n', 'No')], db_column='Suspendido', max_length=1),
        ),
    ]
