# Generated by Django 2.2.7 on 2019-11-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavirtual', '0002_auto_20191114_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='externalURL',
            field=models.URLField(blank=True),
        ),
    ]
