# Generated by Django 2.2.7 on 2019-11-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendavirtual', '0003_productos_externalurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='externalURL',
        ),
    ]
